@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

  package "Parser Classes" as ParserClasses {
  }

  Class CommandResult
  Class "{abstract}\nCommand" as Command

  Class XYZCommand

  Class "<<interface>>\nLogic" as Logic
  Class LogicManager
}

package Model {
  Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" ParserClasses

' Parser creates commands
ParserClasses ..> XYZCommand : <<create>>

' Commands extend Command
XYZCommand -up-|> Command

LogicManager .left.> Command : <<call>>

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : <<create>>

note right of Command
Command implementations include:
AddCommand, AddSupplierCommand, DeleteCommand, EditCommand, FindCommand
TagCommand, OpenCommand, UndoCommand, RedoCommand, RemarkCommand, FavCommand
end note

@enduml
