@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

  package "Parser Classes" as ParserClasses {
    Class AddressBookParser
    Class AddCommandParser
    Class AddSupplierCommandParser
    Class DeleteCommandParser
    Class EditCommandParser
    Class FindCommandParser
    Class TagCommandParser
    Class OpenCommandParser
    Class UndoCommandParser
    Class RedoCommandParser
    Class RemarkCommandParser
    Class FavCommandParser
  }

  Class CommandResult
  Class "{abstract}\nCommand" as Command

  Class AddCommand
  Class AddSupplierCommand
  Class DeleteCommand
  Class EditCommand
  Class FindCommand
  Class TagCommand
  Class OpenCommand
  Class UndoCommand
  Class RedoCommand
  Class RemarkCommand
  Class FavCommand

  Class "<<interface>>\nLogic" as Logic
  Class LogicManager
}

package Model {
  Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" ParserClasses

' Parser creates commands
ParserClasses ..> AddCommand : <<create>>
ParserClasses ..> AddSupplierCommand : <<create>>
ParserClasses ..> DeleteCommand : <<create>>
ParserClasses ..> EditCommand : <<create>>
ParserClasses ..> FindCommand : <<create>>
ParserClasses ..> TagCommand : <<create>>
ParserClasses ..> OpenCommand : <<create>>
ParserClasses ..> UndoCommand : <<create>>
ParserClasses ..> RedoCommand : <<create>>
ParserClasses ..> RemarkCommand : <<create>>
ParserClasses ..> FavCommand : <<create>>

' Commands extend Command
AddCommand -up-|> Command
AddSupplierCommand -up-|> Command
DeleteCommand -up-|> Command
EditCommand -up-|> Command
FindCommand -up-|> Command
TagCommand -up-|> Command
OpenCommand -up-|> Command
UndoCommand -up-|> Command
RedoCommand -up-|> Command
RemarkCommand -up-|> Command
FavCommand -up-|> Command

LogicManager .left.> Command : <<call>>

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : <<create>>

note right of Command
Command implementations include:
AddCommand, AddSupplierCommand, FindCommand,
EditCommand, DeleteCommand, TagCommand, OpenCommand,
UndoCommand, RedoCommand, RemarkCommand, FavCommand
end note

@enduml
