@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command

Class MultiArgCommand
Class IndexArgCommand

package "Parser classes" {
  Class "<<interface>>\nParser" as Parser
  Class AddressBookParser

  Class MultiArgCommandParser
  Class IndexArgCommandParser

  Class CliSyntax
  Class ParserUtil
  Class ArgumentMultimap
  Class ArgumentTokenizer
  Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

' AddressBookParser creates the relevant command parser (for commands that need parsing)
AddressBookParser .down.> MultiArgCommandParser : <<create>>
AddressBookParser .down.> IndexArgCommandParser : <<create>>

' AddressBookParser uses Command (returns Command)
AddressBookParser ..> Command : <<use>>

' Each concrete parser creates a Command
MultiArgCommandParser ..> MultiArgCommand : <<create>>
IndexArgCommandParser ..> IndexArgCommand : <<create>>

' Parsers implement Parser interface
MultiArgCommandParser .up.|> Parser
IndexArgCommandParser .up.|> Parser

' Shared parsing utilities used by parsers

MultiArgCommandParser ..> ArgumentMultimap
MultiArgCommandParser ..> ArgumentTokenizer
MultiArgCommandParser ..> CliSyntax
MultiArgCommandParser ..> ParserUtil

IndexArgCommandParser ..> ParserUtil

ArgumentTokenizer .left.> ArgumentMultimap
CliSyntax ..> Prefix
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix

' Commands extend Command
MultiArgCommand -up-|> Command
IndexArgCommand -up-|> Command

@enduml
